"""empty message

Revision ID: 0789d9be6de7
Revises: bb876e4a2dcd
Create Date: 2025-05-13 17:42:06.973259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0789d9be6de7'
down_revision: Union[str, None] = 'bb876e4a2dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('interval', sa.Interval(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'interval')
    # ### end Alembic commands ###
