"""empty message

Revision ID: 635fb0ad4c12
Revises: 3c8ad50aaf2c
Create Date: 2025-05-12 19:27:28.897229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '635fb0ad4c12'
down_revision: Union[str, None] = '3c8ad50aaf2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PHOTO', 'VIDEO', 'AUDIO', name='messagemediatypes').create(op.get_bind())
    sa.Enum('BUILDING', 'SENDING', 'FINISHED', 'WAITING', name='messagestatus').create(op.get_bind())
    sa.Enum('EN', 'UZ', 'RU', name='userlanguages').create(op.get_bind())
    sa.Enum('ADMIN', 'USER', name='userprivileges').create(op.get_bind())
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('inx_key', 'bot_settings', ['key'], unique=False)
    op.create_index('inx_value', 'bot_settings', ['value'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('privilege', postgresql.ENUM('ADMIN', 'USER', name='userprivileges', create_type=False), server_default='USER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('language', postgresql.ENUM('EN', 'UZ', 'RU', name='userlanguages', create_type=False), server_default='UZ', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('link', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', postgresql.ENUM('BUILDING', 'SENDING', 'FINISHED', 'WAITING', name='messagestatus', create_type=False), server_default='BUILDING', nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('interval', sa.Interval(), server_default=sa.text("INTERVAL '1 hour'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_accounts',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'user_id')
    )
    op.create_table('message_accounts',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'message_id')
    )
    op.create_table('message_groups',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'message_id')
    )
    op.create_table('message_media',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_token', sa.String(), nullable=False),
    sa.Column('content_type', postgresql.ENUM('PHOTO', 'VIDEO', 'AUDIO', name='messagemediatypes', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_media')
    op.drop_table('message_groups')
    op.drop_table('message_accounts')
    op.drop_table('user_accounts')
    op.drop_table('messages')
    op.drop_table('groups')
    op.drop_table('users')
    op.drop_index('inx_value', table_name='bot_settings')
    op.drop_index('inx_key', table_name='bot_settings')
    op.drop_table('bot_settings')
    op.drop_table('accounts')
    sa.Enum('ADMIN', 'USER', name='userprivileges').drop(op.get_bind())
    sa.Enum('EN', 'UZ', 'RU', name='userlanguages').drop(op.get_bind())
    sa.Enum('BUILDING', 'SENDING', 'FINISHED', 'WAITING', name='messagestatus').drop(op.get_bind())
    sa.Enum('PHOTO', 'VIDEO', 'AUDIO', name='messagemediatypes').drop(op.get_bind())
    # ### end Alembic commands ###
