"""empty message

Revision ID: ae5b20d3c598
Revises: 9c089957f121
Create Date: 2025-05-13 17:40:52.430907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5b20d3c598'
down_revision: Union[str, None] = '9c089957f121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('interval', sa.Interval(), server_default="INTERVAL '1 hour", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'interval')
    # ### end Alembic commands ###
