"""empty message

Revision ID: bb876e4a2dcd
Revises: ae5b20d3c598
Create Date: 2025-05-13 17:41:34.783989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb876e4a2dcd'
down_revision: Union[str, None] = 'ae5b20d3c598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('interval', sa.Interval(), server_default="INTERVAL '1 hours", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'interval')
    # ### end Alembic commands ###
