"""empty message

Revision ID: e8cbcc5a05ec
Revises: 0789d9be6de7
Create Date: 2025-05-13 18:58:36.784101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8cbcc5a05ec'
down_revision: Union[str, None] = '0789d9be6de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###
